### ISSUE TITLE
AspNetCore.Identity.MongoDB is not compatible with netcoreapp

### ISSUE THREAD

**Issue by dataangel** [tugberkugurlu/AspNetCore.Identity.MongoDB#1]
```
Project AspNetCore.Identity.MongoDB is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project AspNetCore.Identity.MongoDB supports: net461 (.NETFramework,Version=v4.6.1)
One or more projects are incompatible with .NETCoreApp,Version=v1.0.
```

**Comment by tugberkugurlu** [comment]
this is intentional, see README file:

> For the time being, this only works on full .NET desktop CLR on Windows and on Mono on other platforms (Linux, OSx).

Till MongoDB has a .NET Core client, this will stay the same. They seem to be on top of it: https://github.com/mongodb/mongo-csharp-driver/pull/210#issuecomment-213136053. They might get something up soon, I am not entirely sure though.

**Comment by tugberkugurlu** [comment]
track this on https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/issues/2, I will close this here.
