### ISSUE TITLE
fix namespaces

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#10]
Some (or all?) namespaces are `Dnx.Identity.MongoDB`. It should really be `AspNetCore.Identity.MongoDB` or starts with that.

**Comment by runxc1** [comment]
Why not just shorten it to
Identity. MongoDB?

**Comment by tugberkugurlu** [comment]
@runxc1 good suggestion, we could do. I honestly don't like .NET namespace convention or the package naming convention 😞 For example, Go has short package names on core lib: https://golang.org/pkg/ which is amazing considering what we have now: `System.Threading.Tasks`, `System.Security.Claims`, etc. 😞 However, I felt like honoring the ecosystem's convention is more valuable than going rogue.

I liked `Identity.MongoDB` though, let's go with that 👍

**Comment by tugberkugurlu** [comment]
I thought about this and I am leaning towards `AspNetCore.Identity.MongoDB` even if I don't like it :disappointed: It will be consistent with the ASP.NET Core libraries. Otherwise, it will be confusing as this doesn't support ["non-core" Identity](https://www.nuget.org/packages/Microsoft.AspNet.Identity).
