### ISSUE TITLE
"This platform does not support connecting sockets to DNS endpoints" error from MongoDB Client on *nix platforms

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#11]
see https://github.com/mongodb/mongo-csharp-driver/pull/243#issuecomment-242560056 and see https://github.com/StackExchange/StackExchange.Redis/issues/463#issuecomment-241256886 and https://github.com/dotnet/corefx/issues/8768.

This has been fixed apparently and [on master](https://github.com/mongodb/mongo-csharp-driver/commit/9c2097f349d5096a04ea81b0c9ceb60c7e1acee4). We should take the next version of MongoDB Driver ASAP as it makes this library pretty much unusable 😞

**Comment by tverboon** [comment]
For me it only fails with localhost, replacing the connection to 127.0.0.1 and it works on the Mac.

**Comment by tugberkugurlu** [comment]
YES, it made it work! My sample is now also working 😄 

![image](https://cloud.githubusercontent.com/assets/328122/18024232/2e590054-6bfd-11e6-8447-5da19472ab4a.png)

**Comment by tugberkugurlu** [comment]
See this https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/issues/14

**Comment by tugberkugurlu** [comment]
done by 5e1eef80d8ea8eda07480673eba5675ae91213b8
