### ISSUE TITLE
Logins are not registered

### ISSUE THREAD

**Issue by francnuec** [tugberkugurlu/AspNetCore.Identity.MongoDB#18]
I see a "logins" array field on the document in the db, but each subsequent login is not being registered.

Is there a setting?

**Comment by tugberkugurlu** [comment]
No, it should work out by default. Can you give me repro steps or even better: stick a sample in a public repository and share it with me.

**Comment by francnuec** [comment]
I'm actually just playing around with the samples you provided. Nothing different. It's my first time trying out Mongo, so I'm just testing before I use in a proper project.

**Comment by tugberkugurlu** [comment]
Are you logging in with a 3rd Party login provider on the sample?

It should look like this by default when you register with a Password login: https://twitter.com/tourismgeek/status/769346069423587328. However, when you start adding 3rd Party logins (e.g. Twitter, etc.), `logins` array should be filled.

**Comment by francnuec** [comment]
Oh. I see. I always thought the field was logging each local sign in to the app. Thanks.

**Comment by tugberkugurlu** [comment]
@francnuec no problem 😄
