### ISSUE TITLE
Enable running samples through docker-compose up

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#19]
Start with this, which is the only sample: https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/tree/master/samples/IdentitySample.Mvc

It should stand up a MongoDB instance, link it to the application container.

**Comment by dealproc** [comment]
Working on this as part of the IdentityServer sample.  Will go back to the Mvc Sample and enable the same once complete with IdentityServer.
