### ISSUE TITLE
Get a sample with MongoDB replication

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#21]
Would be nice to have this through docker.

**Comment by dealproc** [comment]
@tugberkugurlu what is the concern here?

**Comment by tugberkugurlu** [comment]
This was purely based on assumption that people who engage with ASP.NET Core Identity would need guidance on how to achibe high availibility with MongoDB. However, not a huge concern at all. Can be closed safely I believe.
