### ISSUE TITLE
I think RoleStore absent ..

### ISSUE THREAD

**Issue by CanMehmetK** [tugberkugurlu/AspNetCore.Identity.MongoDB#24]
Need role store,

- Also there is IdentityBuilder what about using it...
    If i want to use multi database with entity framework core then using this may be well..

teşekkürler.

**Comment by tugberkugurlu** [comment]
Dup of https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/pull/6, see the comments there.

Why do you need role store? Why can't you just use claims to store roles?

**Comment by CanMehmetK** [comment]
regarding this page
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles

these is still UserRoleStore implementations in identity..
Surely yes Claims is another option but i guess using role is ansenario beside that calims is another story.

I just need to implement this for dynamic authorization with static roles.
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased

thanks for solution learned some in sample also i changed AddDefaultTokenProviders
like put them in this that contained in ConfigureServices   
services.AddIdentity<IdentityUser, IdentityRole>(options => {
                  options.SignIn.RequireConfirmedEmail
                 options.SignIn.RequireConfirmedPhoneNumber
                 options.Tokens.ChangeEmailTokenProvider
                 options.Tokens.EmailConfirmationTokenProvider

by this way i could see all options together

regards and thnks for code..

**Comment by tugberkugurlu** [comment]
> i guess using role is ansenario beside that calims is another story

What I meant is that you can store the roles as a claim. Doesn't this work?

**Comment by tugberkugurlu** [comment]
related https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/pull/6

**Comment by dealproc** [comment]
@SorenZ Are we able to close this issue?
