### ISSUE TITLE
Configurable collection name

### ISSUE THREAD

**Issue by hman-pro** [tugberkugurlu/AspNetCore.Identity.MongoDB#26]
In some situation I have to use users collection through another collection or in another service except authentication.
Is it possible to pass optional user's collection name to `MongoUserStore` constructor.

**Comment by tugberkugurlu** [comment]
Yep, this should be possible. I have added it to the list of things to do before the stable release but feel free to PR this if you would like to. Let me know if you want to do this 😄

**Comment by hman-pro** [comment]
I'll send a PR today, 
and I'm going to suggest other features in another issue.
this project is awesome 💃 , 
I can not wait to see v 1.0.0.

**Comment by tugberkugurlu** [comment]
@SorenZ 🎉 thanks, keep them coming 😄

**Comment by hman-pro** [comment]
@tugberkugurlu 
I try to do my best, 
if my little knowledge and poor English allow me 😌

**Comment by tugberkugurlu** [comment]
@SorenZ thanks for your contribution! You did good, keep them coming 😄

**Comment by tugberkugurlu** [comment]
this is fixed by #27.
