### ISSUE TITLE
Service Configuration Wrapper

### ISSUE THREAD

**Issue by hman-pro** [tugberkugurlu/AspNetCore.Identity.MongoDB#28]
I think `ConfigureServices ` is a little messy.
Is it a good idea to create an `IServiceCollection `extensions and put all default configuration setting (methods and class) into it and just call it in startup configuration like this `services.AddMongoIdentity(someOptions);` ?!

**Comment by hman-pro** [comment]
solved by #34

**Comment by dealproc** [comment]
@SorenZ Can we close this issue, given you noted [above] that it was solved with #34?
