### ISSUE TITLE
ASP.NET Core Identity 1.0.0 RTM support

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#3]
~~ongoing at https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/tree/rc2~~

Turned this into RTM support issue

**Comment by tugberkugurlu** [comment]
based on https://www.nuget.org/packages/Microsoft.AspNetCore.Identity/1.0.0

**Comment by gdoron** [comment]
What's the current status of the library?
Is it possible to use Identity Core 1.0.0 with Mongo?

I plan to port from EF & SQL to Mongo because of the **currently** very bad performance of EF Core.
I don't care about CoreCLR as I target the full .NET framework.

So is it possible?
How? Is there any some kind of documentation or even a small snippet of how to setup things?

Thanks!

**Comment by tugberkugurlu** [comment]
Hi @gdoron,

I am very keen on getting this running on v1.0.0 bits. However, current MongoDB driver is not supporting .NET Core (see https://github.com/mongodb/mongo-csharp-driver/pull/243#issuecomment-233672092). So, I was waiting for them to release a new version. Otherwise (as the current state of AspNetCore.Identity.MongoDB), it will just work on full desktop framework on Windows and mono on other platforms.

What is your requirement (e.g. CoreCLR)? if you are OK with full desktop framework or mono, I can ship a prerelease package to nuget which would work on those.

> ? Is there any some kind of documentation

Documentation is something I will invest on when the RTM version is up (with samples). Sorry that there is not much now but you can see this old sample: https://github.com/tugberkugurlu/Identity/tree/beta8-mongodb/samples/IdentitySample.Mvc in order to understand how the wiring is done.

**Comment by gdoron** [comment]
Thanks for your quick reply @tugberkugurlu !

> What is your requirement (e.g. CoreCLR)? if you are OK with full desktop framework or mono, I can ship a prerelease package to nuget which would work on those.

As I commented earlier, _I don't care about CoreCLR as I target the full .NET framework._
Obviously it would be nice if it could run on netstandard and  Linux, but anyway I'm not going to run on non windows machines until there will be more case studies.

Do you think the libaray is mature enough to run on production?
Or do you suggest me to keep using EF & SQL for Identity and use Mongo for all the other stuff?

Thanks again!

**Comment by tugberkugurlu** [comment]
@gdoron awesome, I will get onto it this evening and publish a pre-release package today which will work on mono/full desktop .NET framework :+1: I will mainly evolve https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/tree/rc2 branch to target RTM. I will also try to get some samples and docs up so that it would be a smooth process to integrate.

Sorry for the wait, if I don't get back till tomorrow, please do ask again. I am so busy nowadays, I may forget :cry:

**Comment by gdoron** [comment]
@tugberkugurlu Awesome,I can't wait giving it a try.
I just want to make sure you saw my other question:

> Do you think the libaray is mature enough to run on production?
> Or do you suggest me to keep using EF & SQL for Identity and use Mongo for all the other stuff?

I would be happy if you could answer that question too when you'll have the time.

THANKS!

**Comment by tugberkugurlu** [comment]
> Do you think the libaray is mature enough to run on production?

I don't know :smile: I will use it on prod and if there are any bugs I see along the way, I plan to fix them here. I would say start using it and log any issues here. I would suggest to write integration tests using something like https://github.com/tugberkugurlu/MongoDB.Testing and see if there are any abnormalities with it.

> Or do you suggest me to keep using EF & SQL for Identity and use Mongo for all the other stuff?

It's up to you. If SQL Server covers your cases, you can go with that.

**Comment by tugberkugurlu** [comment]
Sorry for being late, there is a PR on this now: https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/pull/5

**Comment by tugberkugurlu** [comment]
this is done, see #7. I hope to get some samples added soon (#8).
