### ISSUE TITLE
Put testing infrastructure in place

### ISSUE THREAD

**Issue by hman-pro** [tugberkugurlu/AspNetCore.Identity.MongoDB#33]
I think a unit test project just like [asp.net/identity](https://github.com/aspnet/Identity/tree/dev/test) is require, in order to test changes with real data on database.

**Comment by tugberkugurlu** [comment]
YES, it would be really good 👍 Doesn't have to be unit tests, it can even directly hit MongoDB by using https://github.com/tugberkugurlu/MongoDB.Testing

I believe Travis CI has MonogDB support within it. So, it's easy to run them on the build server too.

**Comment by hman-pro** [comment]
I do agree.
If you provide me require infrastructure (I mean projects and ...) I will continue on it.

**Comment by tugberkugurlu** [comment]
@SorenZ I am on it now, will put the structure in place.

**Comment by tugberkugurlu** [comment]
fixed by #37.

**Comment by hman-pro** [comment]
great job 👍
