### ISSUE TITLE
How do you wire this up in the Startup.cs file

### ISSUE THREAD

**Issue by runxc1** [tugberkugurlu/AspNetCore.Identity.MongoDB#4]
So how do you wire this up in the Startup.cs file if you just created a new project?

**Comment by tugberkugurlu** [comment]
hey, see this: https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/issues/3#issuecomment-235255279

I will get some docs up this evening hopefully :fingers_crossed:

**Comment by runxc1** [comment]
Do you have a test website that you are using this in?  It would be nice to see that.

**Comment by tugberkugurlu** [comment]
@runxc1 I used this at https://github.com/tugberkugurlu/ModernShopping/tree/master/Auth/src/ModernShopping.Auth which is a bit old now.

See this part https://github.com/tugberkugurlu/ModernShopping/blob/master/Auth/src/ModernShopping.Auth/Startup.cs#L58-L91.

**Comment by runxc1** [comment]
Yeah I finally dug into it and figured it out and added an extension method to help configure it to make it easier, similar to what the EF provider and many other do

**Comment by tugberkugurlu** [comment]
Cool, I track adding a sample on #8. Feel free to reopen or comment on #8 if you still have questions regarding this.
