### ISSUE TITLE
Update to asp core 1.1

### ISSUE THREAD

**Issue by dacanizares** [tugberkugurlu/AspNetCore.Identity.MongoDB#46]
I'm getting errors when I try to update the sample project to use it on the recently released stable version of VS2017 with asp core 1.1.

**Comment by tugberkugurlu** [comment]
What are the errors and what did you try to do?

**Comment by dacanizares** [comment]
I'm modifying the default project that VS2017 creates and I'm getting errors with this line in startup.cs:

services.TryAddSingleton<IUserClaimsPrincipalFactory<MongoIdentityUser>, UserClaimsPrincipalFactory<MongoIdentityUser>>();

It says that UserClaimsPrincipalFactory requires 2 arguments. It also can't found AddDefaultTokenProviders a couple of lines after.

**Comment by tugberkugurlu** [comment]
> I'm modifying the default project that VS2017 creates and I'm getting errors with this line in startup.cs:
> 
> services.TryAddSingleton<IUserClaimsPrincipalFactory, UserClaimsPrincipalFactory>();

That probably because you don't have this in: https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/blob/c3c91067332852b63fdfad5fd3254dba6ec2800e/samples/IdentitySample.Mvc/Startup.cs#L171-L229

**Comment by tugberkugurlu** [comment]
> It also can't found AddDefaultTokenProviders a couple of lines after.

Same as before, it comes from https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/blob/c3c91067332852b63fdfad5fd3254dba6ec2800e/samples/IdentitySample.Mvc/Startup.cs#L151-L159

**Comment by dacanizares** [comment]
Thanks! Sorry, I haven't seen that before. It worked perfectly.
