### ISSUE TITLE
Any chance of a Core 2.0 of this repo?

### ISSUE THREAD

**Issue by Mech0z** [tugberkugurlu/AspNetCore.Identity.MongoDB#47]
Just wonder if I should just use this one and upgrade to 2.0 afterwards

**Comment by tugberkugurlu** [comment]
Hey, I have been think about upgrading to v2 for a while now but not sure what is changed there for store interface. Maybe 1 impl of store should work for v2 as well?

If you want to give it a go, that's totally fine! Just let me know and send a PR afterwards.

We should at least upgrade to .NET SDK 2.0.

**Comment by Mech0z** [comment]
Can try to look at it, but security aint my forcé, which is why I am looking at packages like this :) but if its mostly upgrade and maybe calling it from a new setup method in startup then it should be fine

**Comment by vladimir-kucher** [comment]
Hey. I've ported it to .net core 2.0 + visual studio 2017. Can I put a PR?

**Comment by tugberkugurlu** [comment]
Yes, please do :tada:

**Comment by vladimir-kucher** [comment]
It seems that patch-version.sh is failing. Since there is no porject.json file exists for .net core 2.0 I am not familiar with build scripts. Can you take a look please?

**Comment by tugberkugurlu** [comment]
Ah, that's expected. Thanks for letting me know, I will take a look!

**Comment by tugberkugurlu** [comment]
@vladimir-kucher's amazing work on #48 and after that, doing #50 resolved this issue 🎊

**Comment by razzeee** [comment]
So will you push this to nuget (as a preview) or what are the steps that will have to happen now?

**Comment by tugberkugurlu** [comment]
A few things are not working with the sample like https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/issues/49. As soon as we have the sample working, I can push a new version to NuGet.

**Comment by tugberkugurlu** [comment]
@Razzeee let me know if you want to give it a try on making the sample work

**Comment by razzeee** [comment]
I don't think I have the skillset/time required for that.

**Comment by tugberkugurlu** [comment]
No worries, I will spend some time to make that work. Will ping you when I am done so that you would have a chance to try it out as well?

**Comment by razzeee** [comment]
Sure, sounds fine

**Comment by agc93** [comment]
Any news on getting this pushed to NuGet? Maybe another prerelease version at least so people can try it out?
