### ISSUE TITLE
Implement IUserAuthenticatorKeyStore<User>

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#49]
![image](https://user-images.githubusercontent.com/328122/30243713-dc27f9e0-95a7-11e7-8bf3-0612bf5e2686.png)

**Comment by tobieheyns** [comment]
I implemented IUserAuthenticatorKeyStore and IUserTwoFactorRecoveryCodeStore on the MongoUserStore. The above error no longer haunts me. Busy testing the code to see if all is working.  I submitted the changes to my my cloned repo.

Your comments will be appreciated.

**Comment by Farshidgolkarihagh** [comment]
Hi, Any update on this? You feedback is appreciated

**Comment by tugberkugurlu** [comment]
@Farshidgolkarihagh yep, looking at the PR #53 now.

**Comment by Mech0z** [comment]
Anyone got this working?

**Comment by dealproc** [comment]
I believe #53 closes this.  I've merged @tcheyns code, and am looking at the last of the requests I had for him with regard to this.
